version: '3.7'

services:
    postgres:
        image: postgres:11
        restart: always
        container_name: postgres
        environment:
            - POSTGRES_USER=bde_lab_1
            - POSTGRES_PASSWORD=bde_lab_1
            - POSTGRES_DB=postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    jupyter:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: jupyter_docker
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=yes
        volumes:
            - ./:/home/jovyan/work
        depends_on: 
            - postgres
